<a href="https://colab.research.google.com/github/atiksha2528/Integer-floats-booleans/blob/main/numPY_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#load the numpy
import numpy as np
#create a 2D array
arravali= np.array (np.random.randint(10,45,(8,2)))
print(f"the defined array is \n{arravali}")
print(f"\n the shape of the array is {arravali.shape}")

the defined array is 
[[23 14]
 [11 25]
 [11 41]
 [33 28]
 [20 16]
 [40 36]
 [16 10]
 [13 36]]

 the shape of the array is (8, 2)


In [ ]:
#Storing the transpose in another matrix object
nilgiri = np.transpose(arravali)
print(f" This transpose of the array is \n{nilgiri}")
print(f" \n The shape of the array is {nilgiri.shape}")

 This transpose of the array is 
[[23 11 11 33 20 40 16 13]
 [14 25 41 28 16 36 10 36]]
 
 The shape of the array is (2, 8)


In [ ]:
#3D Array

random_3d_array = np.array(np.random.randint(10,45,(3,2,4)))
print(f"The defined array is \n{random_3d_array}")
print(f" \n The shape of the array is {random_3d_array.shape}")

The defined array is 
[[[11 22 23 20]
  [14 24 20 27]]

 [[41 12 18 13]
  [30 18 10 17]]

 [[21 11 38 16]
  [15 33 20 24]]]
 
 The shape of the array is (3, 2, 4)


In [ ]:
#Storing the transpose of the created 3D Array

transpose_3d_array = np.transpose(random_3d_array)
print(f" This transpose of the array is \n{transpose_3d_array}")
print(f" \n The shape of the array is {transpose_3d_array.shape}")

 This transpose of the array is 
[[[11 41 21]
  [14 30 15]]

 [[22 12 11]
  [24 18 33]]

 [[23 18 38]
  [20 10 20]]

 [[20 13 16]
  [27 17 24]]]
 
 The shape of the array is (4, 2, 3)


In [ ]:
#Create a two dimensional array

random_cohort = np.array(np.random.randint(10,45,(3,8)))
print(f"The defined array is \n{random_cohort}")
print(f" \n The shape of the array is {random_cohort.shape}")

The defined array is 
[[20 44 25 22 43 29 14 41]
 [36 14 34 41 13 24 20 37]
 [12 20 19 14 22 23 35 14]]
 
 The shape of the array is (3, 8)


In [ ]:
#Now we can reshape this to 1D,2D or 3D Array

new_shape = (2,6,2)
reshaped_random_cohort = np.reshape(random_cohort,new_shape)
print(f"This reshaped array is \n{reshaped_random_cohort}")
print(f" \n The shape of the array is {reshaped_random_cohort.shape}")

This reshaped array is 
[[[20 44]
  [25 22]
  [43 29]
  [14 41]
  [36 14]
  [34 41]]

 [[13 24]
  [20 37]
  [12 20]
  [19 14]
  [22 23]
  [35 14]]]
 
 The shape of the array is (2, 6, 2)


In [ ]:
new_shape = (2,-1,6)
reshaped_random_cohort = np.reshape(random_cohort,new_shape)
print(f"This reshaped array is \n{reshaped_random_cohort}")
print(f" \n The shape of the array is {reshaped_random_cohort.shape}")

This reshaped array is 
[[[20 44 25 22 43 29]
  [14 41 36 14 34 41]]

 [[13 24 20 37 12 20]
  [19 14 22 23 35 14]]]
 
 The shape of the array is (2, 2, 6)


In [ ]:
random_3D_cohort = np.array(np.random.randint(10,45,(3,6,2)))
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[20 31]
  [17 40]
  [27 38]
  [20 17]
  [33 32]
  [34 39]]

 [[22 36]
  [40 32]
  [20 39]
  [29 11]
  [13 28]
  [34 10]]

 [[20 43]
  [23 14]
  [39 13]
  [38 19]
  [44 19]
  [28 19]]]
 
 The shape of the array is (3, 6, 2)


In [ ]:
new_shape = (2,1,6)
resize_random_3D_cohort = np.resize(random_3D_cohort,new_shape)
print(f"This resized array is \n{resize_random_3D_cohort}")
print(f" \n The shape of the array is {resize_random_3D_cohort.shape}")

This resized array is 
[[[20 31 17 40 27 38]]

 [[20 17 33 32 34 39]]]
 
 The shape of the array is (2, 1, 6)


In [ ]:
random_3D_cohort = np.array(np.random.randint(10,45,(2,4,6)))
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[13 14 31 44 32 17]
  [38 30 11 18 24 42]
  [12 35 38 20 14 15]
  [21 23 12 19 35 42]]

 [[24 27 18 23 44 27]
  [11 35 39 17 17 19]
  [12 39 13 34 20 14]
  [34 26 42 41 26 28]]]
 
 The shape of the array is (2, 4, 6)


In [ ]:
new_shape = (2,3,6)
resized_random_3D_cohort = np.resize(random_3D_cohort,new_shape)
print(f"This resized array is \n{resize_random_3D_cohort}")
print(f" \n The shape of the array is {resize_random_3D_cohort.shape}")

This resized array is 
[[[20 31 17 40 27 38]]

 [[20 17 33 32 34 39]]]
 
 The shape of the array is (2, 1, 6)


In [ ]:
import numpy as np
random_3D_cohort = np.array(np.random.randint(10,45,(2,4,6)))
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[11 38 30 13 14 39]
  [39 17 42 16 17 34]
  [44 28 39 15 34 26]
  [34 43 30 29 16 40]]

 [[29 44 14 36 18 32]
  [36 18 19 12 35 17]
  [21 21 27 24 16 20]
  [21 30 30 32 11 40]]]
 
 The shape of the array is (2, 4, 6)


In [ ]:
new_shape = (2,3,6)
resized_random_3D_cohort = np.resize(random_3D_cohort,new_shape)
print(f"This resized array is \n{resized_random_3D_cohort}")
print(f" \n The shape of the array is {resized_random_3D_cohort.shape}")

This resized array is 
[[[11 38 30 13 14 39]
  [39 17 42 16 17 34]
  [44 28 39 15 34 26]]

 [[34 43 30 29 16 40]
  [29 44 14 36 18 32]
  [36 18 19 12 35 17]]]
 
 The shape of the array is (2, 3, 6)


In [ ]:
import numpy as np
a = np.random.randint(10,20,(2,3,4))   #Axis 0-2 ; Axis 1-3 ; Axis 2-4
print(a)
print(a.shape)

[[[16 14 13 15]
  [13 13 10 12]
  [19 13 10 19]]

 [[19 11 18 11]
  [18 16 16 15]
  [10 16 10 17]]]
(2, 3, 4)


In [ ]:
#Insert along axis = 0
np.insert(a,1,100,axis=0)

array([[[ 16,  14,  13,  15],
        [ 13,  13,  10,  12],
        [ 19,  13,  10,  19]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[ 19,  11,  18,  11],
        [ 18,  16,  16,  15],
        [ 10,  16,  10,  17]]])

In [ ]:
a = np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[4 3 2]
  [2 2 5]
  [4 3 5]]

 [[3 3 3]
  [3 4 3]
  [5 2 3]]]
(2, 3, 3)


In [ ]:
np.append(a,50)

array([ 4,  3,  2,  2,  2,  5,  4,  3,  5,  3,  3,  3,  3,  4,  3,  5,  2,
        3, 50])

In [ ]:
b = np.random.randint(2,6,(2,1,3))
print(b)

[[[5 2 5]]

 [[3 3 5]]]


In [ ]:
print(a)
print(a.shape)

[[[4 3 2]
  [2 2 5]
  [4 3 5]]

 [[3 3 3]
  [3 4 3]
  [5 2 3]]]
(2, 3, 3)


In [ ]:
np.append(a,b,axis=1)

array([[[4, 3, 2],
        [2, 2, 5],
        [4, 3, 5],
        [5, 2, 5]],

       [[3, 3, 3],
        [3, 4, 3],
        [5, 2, 3],
        [3, 3, 5]]])

In [ ]:
import numpy as np
a = np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[3 2 2]
  [5 5 2]
  [3 3 2]]

 [[4 2 2]
  [2 4 4]
  [4 4 3]]]
(2, 3, 3)


In [ ]:
np.delete(a,(0),axis = 0)

array([[[4, 2, 2],
        [2, 4, 4],
        [4, 4, 3]]])

In [ ]:
np.delete(a,(0,2),axis = 1)

array([[[5, 5, 2]],

       [[2, 4, 4]]])

In [ ]:
a

array([[[3, 2, 2],
        [5, 5, 2],
        [3, 3, 2]],

       [[4, 2, 2],
        [2, 4, 4],
        [4, 4, 3]]])

In [ ]:
np.delete(a,(0,1),axis = 2)

array([[[2],
        [2],
        [2]],

       [[2],
        [4],
        [3]]])

In [ ]:
a = np.random.randint(2,20,(2,3,3))
print(a)
print(a.shape)

[[[17  8  8]
  [ 3 17 19]
  [ 8  8  2]]

 [[18 12  4]
  [ 6  7 15]
  [ 3 16  2]]]
(2, 3, 3)


In [ ]:
np.unique(a)

array([ 2,  3,  4,  6,  7,  8, 12, 15, 16, 17, 18, 19])

In [ ]:
np.unique(a,return_counts=True)

(array([ 2,  3,  4,  6,  7,  8, 12, 15, 16, 17, 18, 19]),
 array([2, 2, 1, 1, 1, 4, 1, 1, 1, 2, 1, 1]))

In [ ]:
np.unique(a,return_counts=True,return_index=True)

(array([ 2,  3,  4,  6,  7,  8, 12, 15, 16, 17, 18, 19]),
 array([ 8,  3, 11, 12, 13,  1, 10, 14, 16,  0,  9,  5]),
 array([2, 2, 1, 1, 1, 4, 1, 1, 1, 2, 1, 1]))

In [ ]:
a = [1,2,3]
b= a
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[10, 2, 3]


In [ ]:
a = np.array([2,34,12])
b = a
b[0] = -999
print(b)
print(a)

[-999   34   12]
[-999   34   12]


In [ ]:
a = np.array([2,34,12])
b = a.copy()
b[0] = -999
print(b)
print(a)

[-999   34   12]
[ 2 34 12]


In [ ]:
np.arange(3) + 5

array([5, 6, 7])

In [ ]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
np.arange(3).reshape((3,1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
np.arange(2)

array([0, 1])

In [ ]:
a = np.random.randint(2,6,(2,4))
print(a)
b = np.random.randint(1,10,(2,2))
print(b)

[[3 4 3 4]
 [4 4 5 4]]
[[6 2]
 [2 8]]


In [ ]:
a = np.random.randint(2,6,(2,4))
print(a)
b = np.random.randint(0,5,(2,4))
print(b)

[[4 2 5 3]
 [4 2 2 3]]
[[3 4 2 2]
 [3 4 4 2]]


In [ ]:
np.multiply(a,b)

array([[12,  8, 10,  6],
       [12,  8,  8,  6]])

In [ ]:
np.divide(a,b)



array([[1.33333333, 0.5       , 2.5       , 1.5       ],
       [1.33333333, 0.5       , 0.5       , 1.5       ]])

In [ ]:
a=np.random.randint(5,9,(2,4))
print(a)

[[6 6 8 8]
 [5 7 7 8]]


In [ ]:
print(np.sum(a))
print(np.sum(a,axis = 0))
print(np.sum(a,axis = 1))

55
[11 13 15 16]
[28 27]


In [ ]:
print(np.min(a))
print(np.min(a,axis=1)) #Across Column
a =np.random.randint(0,20,(3,3))
print(a)

5
[6 5]
[[ 9  9 10]
 [11  2  2]
 [ 2  0  4]]


In [ ]:
print(np.sort(a,axis=0)) # Ascending

[[ 2  0  2]
 [ 9  2  4]
 [11  9 10]]


In [ ]:
print(np.sort(a,axis=1))

[[ 9  9 10]
 [ 2  2 11]
 [ 0  2  4]]


In [ ]:
print(-np.sort(-a,axis=1)) #Descending

[[10  9  9]
 [11  2  2]
 [ 4  2  0]]


In [ ]:
sum(np.arange(3)*np.arange(3).transpose())

5